baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My Webcomic'

[params]
description = 'A minimal webcomic template built with Bootstrap and Hugo.'
[params.author]
name = 'My Name'

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menu.main]]
name = 'About'
pageRef = '/about'
weight = 2
