baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Mini Webcomic'

[params]
description = 'A minimal webcomic template built with Bootstrap and Hugo.'
dateFormat = 'Jan 2, 2006'
comicResizeWidth = 1280
comicThumbResizeWidth = 300
imgFormat = 'jpg'
[params.author]
name = 'Your Name'

[taxonomies]

[[menu.main]]
name = 'Home'
pageRef = '/'
weight = 1

[[menu.main]]
name = 'About'
pageRef = '/about'
weight = 2

[[menu.main]]
name = 'Archive'
pageRef = '/archive'
weight = 3

[imaging]
resampleFilter = 'Lanczos'
quality = 75

[caches]
[caches.images]
dir = ':cacheDir/images'
